Repository MLH-Fellowship/Fellowship-Companion, pull requests merged in 2020-07, with the labels that each got.

#3 Setup basic django app
  server/companion/__init__.py
  server/companion/asgi.py
  server/companion/settings.py
  server/companion/urls.py
  server/companion/wsgi.py
  server/manage.py
Labels: backend

#7 Lakshya/demo endpoints
  .gitignore
  server/companion/api/__init__.py
  server/companion/api/urls.py
  server/companion/api/views.py
  server/companion/settings.py
  server/companion/urls.py
Labels: backend

#6 Create basic React app
  client/.gitignore
  client/README.md
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/components/App/App.css
  client/src/components/App/App.js
  client/src/components/App/App.test.js
  client/src/components/App/logo.svg
  client/src/index.css
  client/src/index.js
  client/src/serviceWorker.js
  client/src/setupTests.js
  client/yarn.lock
Labels: frontend

#18 Add open source license
  LICENSE
Labels: documentation

#17 Set up Material-UI
  client/package.json
  client/public/index.html
  client/src/components/App/App.css
  client/src/components/App/App.js
  client/src/components/App/App.test.js
  client/src/components/App/logo.svg
  client/src/index.css
  client/src/index.js
  client/yarn.lock
Labels: dependencies, design, frontend

#24 Create the main theme
  client/src/components/App/App.js
Labels: design, frontend

#26 Set up React Router DOM
  client/package.json
  client/src/components/App/App.js
  client/src/components/Navigation/Navigation.js
  client/yarn.lock
Labels: frontend

#38 Allow all hosts to access server remotely
  server/src/companion/settings.py
Labels: backend, enhancement

#37 Add local set up instructions
  client/README.md
Labels: documentation, frontend

#44 Create homepage
  client/package.json
  client/src/components/Classes/Classes.js
  client/src/components/Home/Cover.js
  client/src/components/Home/Fellows.js
  client/src/components/Home/Home.js
  client/src/components/Home/LinesOfCode.js
  client/src/components/Home/Projects.js
  client/src/components/Navigation/Navigation.js
  client/yarn.lock
Labels: design, frontend

#50 Add navigation bar and footer
  client/src/components/App/App.js
  client/src/components/App/Footer.js
  client/src/components/App/Navigation.js
  client/src/components/App/NavigationBar.js
  client/src/components/Classes/Classes.js
Labels: design, frontend

#72 Configure Netlify's redirects
  client/public/_redirects
Labels: frontend

#73 Enable CORS
  .gitignore
  server/requirements.txt
  server/src/companion/settings.py
Labels: backend, enhancement

#69 Fetch and display data from the API
  client/src/components/App/Footer.js
  client/src/components/ErrorSnackbar/ErrorSnackbar.js
  client/src/components/Home/Cover.js
  client/src/components/Home/DataBlock.js
  client/src/components/Home/Fellows.js
  client/src/components/Home/Home.js
  client/src/components/Home/LinesOfCode.js
  client/src/components/Home/Projects.js
  client/src/logic/api.js
Labels: frontend

#75 Upgrade dependencies
  client/yarn.lock
Labels: dependencies, frontend

#86 Update `BASE_API_URL`
  client/src/logic/api.js
Labels: frontend

#90 Add contributions page
  client/package.json
  client/src/components/App/Navigation.js
  client/src/components/Contributions/ContributionCard.js
  client/src/components/Contributions/Contributions.js
  client/src/logic/api.js
  client/src/logic/date-time.js
  client/yarn.lock
Labels: design, frontend

#111 Fix link
  README.md
Labels: documentation

#116 Highlight active section
  client/src/components/App/NavigationBar.js
Labels: frontend

#117 Create fellows page
  client/src/components/App/Navigation.js
  client/src/components/Classes/Classes.js
  client/src/components/Fellows/FellowCard.js
  client/src/components/Fellows/Fellows.js
  client/src/logic/api.js
Labels: design, frontend

#119 Create projects page
  client/src/components/App/Navigation.js
  client/src/components/Projects/ProjectCard.js
  client/src/components/Projects/Projects.js
  client/src/logic/api.js
Labels: design, frontend

#123 Don't crop organizations' avatars
  client/src/components/Projects/ProjectCard.js
Labels: design, discussion, frontend

#125 Last front end adjustments
  README.md
  client/package.json
  client/public/favicon.ico
  client/public/home.png
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/src/components/Contributions/Contributions.js
  client/src/index.js
Labels: frontend
